def main():
    raise Exception("Test")